apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: etcd
  name: etcd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - image: appcelerator/etcd
        imagePullPolicy: IfNotPresent
        name: etcd
        ports:
        - containerPort: 2379
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
  name: etcd
  namespace: default
spec:
  ports:
  - name: etcd
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd
  type: ClusterIP
