apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pitaya-admin
  name: pitaya-admin
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pitaya-admin
  template:
    metadata:
      labels:
        app: pitaya-admin
    spec:
      containers:
      - image: tfgco/pitaya-admin:5435941
        imagePullPolicy: IfNotPresent
        name: pitaya-admin
        ports:
        - containerPort: 8000
          protocol: TCP
        env:
        - name: PITAYA_CLUSTER_RPC_CLIENT_NATS_CONNECT
          value: nats://nats.default.svc.cluster.local:4222
        - name: PITAYA_CLUSTER_RPC_SERVER_NATS_CONNECT
          value: nats://nats.default.svc.cluster.local:4222
        - name: PITAYA_CLUSTER_SD_ETCD_ENDPOINTS
          value: etcd.default.svc.cluster.local:2379
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pitaya-admin
  name: pitaya-admin
  namespace: default
spec:
  ports:
  - name: pitaya-admin
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: pitaya-admin
  type: NodePort
